In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("selected_LIDAR_Points_2.txt")

In [3]:
print(df.head())
print(len(df))

   OBJECTID  PointCount  ORIG_FID      POINT_X      POINT_Y  POINT_Z
0       292        3500         1  320453.6419  100970.6548   0.4206
1       293        3500         1  320454.5228  100970.5817   0.3200
2       294        3500         1  320455.4158  100970.5055   0.2499
3       295        3500         1  320456.3180  100970.4293   0.3597
4       296        3500         1  320457.2081  100970.3653   0.6005
14967

In [4]:
west = min(df.POINT_X)
east = max(df.POINT_X)
south = min(df.POINT_Y)
north = max(df.POINT_Y)

In [5]:
tl = (min(df.POINT_X), max(df.POINT_Y))
ew = east - west
ns = north - south
print(tl, ew, ns)

(320396.46740000043, 100970.7036000006) 62.624299999384675 83.26850000025297

In [6]:
window = 3.0

In [7]:
df['index_X'] = np.trunc((df.POINT_X - west) / window)
df['index_Y'] = np.trunc((df.POINT_Y - south) / window)

In [8]:
df.tail()

,OBJECTID,PointCount,ORIG_FID,POINT_X,POINT_Y,POINT_Z,index_X,index_Y
14962,33196,1700,10,320396.7448,100888.2794,10.1895,0.0,0.0
14963,33197,1700,10,320396.6046,100887.6759,4.3708,0.0,0.0
14964,33198,1700,10,320397.3361,100887.7399,1.2497,0.0,0.0
14965,33199,1700,10,320398.2352,100887.6546,1.3503,0.0,0.0
14966,33200,1700,10,320399.1192,100887.5784,1.1704,0.0,0.0

In [9]:
df.astype({"index_X": int, "index_Y": int})

,OBJECTID,PointCount,ORIG_FID,POINT_X,POINT_Y,POINT_Z,index_X,index_Y
0,292,3500,1,320453.6419,100970.6548,0.4206,19,27
1,293,3500,1,320454.5228,100970.5817,0.3200,19,27
2,294,3500,1,320455.4158,100970.5055,0.2499,19,27
3,295,3500,1,320456.3180,100970.4293,0.3597,19,27
4,296,3500,1,320457.2081,100970.3653,0.6005,20,27
5,297,3500,1,320458.0889,100970.2891,0.2713,20,27
6,298,3500,1,320458.9911,100970.2129,0.7315,20,27
7,458,3500,1,320458.3541,100969.3411,0.6401,20,27
8,459,3500,1,320457.4245,100969.4173,0.2408,20,27
9,460,3500,1,320456.5131,100969.4935,0.2012,20,27
10,461,3500,1,320455.6018,100969.5667,0.2286,19,27
11,462,3500,1,320454.6782,100969.6338,0.2896,19,27
12,463,3500,1,320453.7791,100969.7069,0.6187,19,27
13,464,3500,1,320452.8555,100969.7831,0.6309,18,27
14,465,3500,1,320451.9442,100969.8593,0.5791,18,27
15,466,3500,1,320451.0236,100969.9325,0.6096,18,27
16,467,3500,1,320450.1123,100970.0087,0.8199,17,27
17,468,3500,1,320449.1918,100970.0849,0.8291,17,27
18,469,3500,1,320448.2804,100970.1580,0.9601,17,27
19,470,3500,1,320447.3691,100970.2342,0.7894,16,27
20,471,3500,1,320446.4273,100970.3104,0.7711,16,27
21,472,3500,1,320445.5159,100970.3836,0.9815,16,27
22,473,3500,1,320444.5832,100970.4598,0.4907,16,27
23,474,3500,1,320443.6627,100970.5360,0.4694,15,27
24,475,3500,1,320442.7514,100970.6091,0.9296,15,27
25,476,3500,1,320441.8705,100970.6853,2.3012,15,27
26,477,3500,1,320433.1989,100970.6853,9.5799,12,27
27,478,3500,1,320432.9368,100970.6914,2.3012,12,27
28,479,3500,1,320434.0798,100970.6091,9.2690,12,27
29,480,3500,1,320433.8299,100970.6152,2.2799,12,27
...,...,...,...,...,...,...,...,...
14937,33171,1700,10,320416.9469,100887.7674,0.5791,6,0
14938,33172,1700,10,320417.8400,100887.6912,0.6187,7,0
14939,33173,1700,10,320418.7300,100887.6058,0.6187,7,0
14940,33174,1700,10,320419.6322,100887.5205,0.6614,7,0
14941,33175,1700,10,320420.5131,100887.4443,0.4999,8,0
14942,33176,1700,10,320409.6104,100887.4565,1.8501,4,0
14943,33177,1700,10,320408.6503,100887.5510,1.7313,4,0
14944,33178,1700,10,320407.7176,100887.6272,1.8501,3,0
14945,33179,1700,10,320406.7879,100887.7003,2.2311,3,0
14946,33180,1700,10,320405.8156,100887.8070,1.8806,3,0
14947,33181,1700,10,320404.8738,100887.8802,1.9111,2,0
14948,33182,1700,10,320404.1362,100887.7796,6.1996,2,0
14949,33183,1700,10,320403.9320,100887.9655,2.0696,2,0
14950,33184,1700,10,320402.9596,100888.0691,1.7008,2,0
14951,33185,1700,10,320402.0483,100888.1240,2.4415,1,0
14952,33186,1700,10,320401.4113,100887.9259,8.5588,1,0
14953,33187,1700,10,320401.1278,100888.1788,3.0785,1,0
14954,33188,1700,10,320400.4816,100887.9990,8.8697,1,0
14955,33189,1700,10,320400.0854,100888.3526,1.2101,1,0
14956,33190,1700,10,320399.5794,100888.0356,9.8999,1,0
14957,33191,1700,10,320399.1344,100888.4379,1.2802,0,0
14958,33192,1700,10,320398.5766,100888.1788,8.7295,0,0
14959,33193,1700,10,320398.2444,100888.4745,2.3287,0,0
14960,33194,1700,10,320397.7171,100888.1850,10.4486,0,0
14961,33195,1700,10,320397.2812,100888.5568,2.4110,0,0
14962,33196,1700,10,320396.7448,100888.2794,10.1895,0,0
14963,33197,1700,10,320396.6046,100887.6759,4.3708,0,0
14964,33198,1700,10,320397.3361,100887.7399,1.2497,0,0
14965,33199,1700,10,320398.2352,100887.6546,1.3503,0,0
14966,33200,1700,10,320399.1192,100887.5784,1.1704,0,0

In [10]:
pixels = []
for i in range(int(max(df.index_X))):
    for j in range(int(max(df.index_Y))):
        px = df.query(f'(index_X == {i}) & (index_Y == {j})')
        pixels.append([(np.around(x,6),
                        np.around(y,6),
                        np.around(z,6),
                        (i,j)) 
                        for x,y,z in zip(px.POINT_X,
                                         px.POINT_Y,
                                         px.POINT_Z)])

In [11]:
print(len(pixels))

540

In [ ]:
pixNE = []
for x in range(len(pixels)):
    if pixels[x]:
        pixNE.append(pixels[x])

In [ ]:
print([str(x) for x in pixNE[:10]])
print(len(pixNE), type(pixNE))

In [ ]:
pixSet = [set(x) for x in pixNE]

In [ ]:
print(len(pixSet),pixNE[:5])

In [ ]:
with open('minElevLidar2.csv','w') as f:
    for i in pixSet:
        z = []
        for p in i:
            z.append(p[2])
        print(min(z))
        for q in i:
            if q[2] == min(z):
                outString = str(q[:3])[1:-1] + "\n"
                f.write(outString)
                #print(outString)